### ISSUE TITLE
Using TEST_DB where it should be TEST_USER

### ISSUE THREAD

**Issue by raulillana** [wp-cli/wp-cli-tests#146]
Howdy @schlessera!

As we talked yesterday, I'm submitting the bug we found during the #WCEU2022ContributorDay.

It's located in `vendor/wp-cli/wp-cli-tests/bin/install-package-tests` in Line #54.

`mysql -e "CREATE USER IF NOT EXISTS \`${TEST_DB}\`@'%' IDENTIFIED WITH mysql_native_password BY '${TEST_PASSWORD}'" ${HOST_STRING} -u"${USER}" "${PASSWORD_STRING}"`

Should be:

`mysql -e "CREATE USER IF NOT EXISTS \`${TEST_USER}\`@'%' IDENTIFIED WITH mysql_native_password BY '${TEST_PASSWORD}'" ${HOST_STRING} -u"${USER}" "${PASSWORD_STRING}"`

Will send a PR for this ASAP.

**Comment by BhargavBhandari90** [comment]
I think this is done here https://github.com/wp-cli/wp-cli-tests/pull/54
