### ISSUE TITLE
Fix install-package-tests random build failures

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli-tests#160]
Builds fail quite frequently with this error:

```
> install-package-tests
Warning: arning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:32768' (111)
/home/runner/work/extension-command/extension-command/vendor/wp-cli/wp-cli-tests/bin/install-package-tests: 81: [: Illegal number: 
Detected MySQL at version .
+ mysql -e CREATE DATABASE IF NOT EXISTS `wp_cli_test`; -h127.0.0.1 -P32768 --protocol=tcp -uroot -proot
Warning: arning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:32768' (111)
Script install-package-tests handling the prepare-tests event returned with error code 1
Error: Process completed with exit code 1.
```

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/36432/217294637-01e6436d-635b-4925-9e2d-7467d80bc9b4.png">

**Done is:**
* Builds no longer randomly fail with this error.

**Comment by danielbachhuber** [comment]
@wojsmol Just happened again 😞 https://github.com/wp-cli/i18n-command/actions/runs/4177913925/jobs/7236073425#step:11:28

**Comment by danielbachhuber** [comment]
Here's a job where `mysql` never became available: https://github.com/wp-cli/automated-tests/actions/runs/4683019581/jobs/8297593809

<img width="1575" alt="image" src="https://user-images.githubusercontent.com/36432/231602977-10cc64a5-160d-484e-9976-23937aea11ef.png">

`mysql` said it was ready though:

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/36432/231603108-3a72fc86-584d-4a02-82ba-d081c609d4fb.png">

LIES

**Comment by wojsmol** [comment]
@danielbachhuber Please re-enable testing workflow in automated-testing repository.

**Comment by danielbachhuber** [comment]
@wojsmol Ah, the warning message at the top that I just looked past? 😁 I clicked the button.
