### ISSUE TITLE
Use alternative theme for testing as `P2` theme has been retired

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli-tests#200]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

P2 theme has been removed from the directory. Ref: https://themes.trac.wordpress.org/ticket/30322

We need to find more reliable alternative theme for feature tests.

Reference of P2 theme in our tests: https://github.com/search?q=org%3Awp-cli%20%22wp%20theme%20install%20p2%22&type=code

**Comment by tfirdaus** [comment]
@ernilambar the `default` theme could be a good replacement in this case :). I think it's been one of the most iconic theme in WordPress.

**Comment by ernilambar** [comment]
@tfirdaus Since we have already used TwentyTwelve in several tests, may be it would be good replacement. I have updated feature test in `widget` command here. https://github.com/wp-cli/widget-command/pull/61

**Comment by tfirdaus** [comment]
@ernilambar I have it updated in the `extension` command https://github.com/wp-cli/extension-command/pull/417

**Comment by tfirdaus** [comment]
@ernilambar I got a problem in https://github.com/wp-cli/extension-command/pull/417 though, where it says the theme is already installed.

```
005 Scenario: Attempting to delete a theme that doesn't exist # features/theme-delete.feature:110
      And I run `wp theme install twentytwelve`               # features/theme-delete.feature:5
        $ wp theme install twentytwelve
        Success: Theme already installed.
```

What would be the better approach here:

- Should I pick other theme just for this case? 
- Or, should we find an alternative that might work for all theme install scenario in the feature tests?

**Comment by ernilambar** [comment]
Done

- https://github.com/wp-cli/extension-command/pull/417
- https://github.com/wp-cli/scaffold-command/pull/336
- https://github.com/wp-cli/entity-command/pull/494
