### ISSUE TITLE
php-compatibility for phpcs is out of date

### ISSUE THREAD

**Issue by mrsdizzie** [wp-cli/wp-cli-tests#217]
As seen in https://github.com/wp-cli/extension-command/issues/431 the version of php-compatibility used for testing seems out of date. In composer, the dependency looks like:

`"phpcompatibility/php-compatibility": "^9.3.5",`

But https://github.com/PHPCompatibility/PHPCompatibility/ suggests that is from 2019 and it doesn't seem to know about PHP 8 features. Looking at their Github, most work is done on the develop branch and there hasn't been a release in a long time (despite very active development).

So phpcs in wp-cli repos isn't able to warn or flag when somebody introduces a PHP 8 feature into new code (like the [extension-command](https://github.com/wp-cli/extension-command/issues/431) issue above. Likely missing fixes and changes to related to PHp 7 as well. 

I think either they need to make a release we can use, or we need to change our composer dependency to `dev-develop` 

Related: https://github.com/PHPCompatibility/PHPCompatibility/issues/1312

**Comment by mrsdizzie** [comment]
Looks like it would have caught it:

<img width="1512" alt="Screenshot 2024-08-15 at 15 09 17" src="https://github.com/user-attachments/assets/803dd472-e36d-42e0-98ad-6b605f567a82">

**Comment by mrsdizzie** [comment]
Happy to do a PR for this but I'm not sure where it goes because of all the abstraction involved. When I set up http://github.com/wp-cli/wp-cli-dev and do composer install -- most of the `vendor/phpcompatibility` folders symlink back to the main `wp-cli-dev` vendor folder. There is no direct dependency in that projects composer.json, so is it correct that the `phpcompatibility` package is pulled in to `wp-cli-dev` by the composer dependency on this `wp-cli-tests` package [here](https://github.com/wp-cli/wp-cli-dev/blob/main/composer.json#L238) ?

If so, I can submit a PR to update the dep for this repo to use
 `"phpcompatibility/php-compatibility": "dev-develop",`

And see what happens.

**Comment by swissspidy** [comment]
> There is no direct dependency in that projects composer.json, so is it correct that the `phpcompatibility` package is pulled in to `wp-cli-dev` by the composer dependency on this `wp-cli-tests` package [here](https://github.com/wp-cli/wp-cli-dev/blob/main/composer.json?rgh-link-date=2024-08-16T14%3A29%3A49Z#L238) ?

Yes:

```
$ composer why phpcompatibility/php-compatibility
wp-cli/wp-cli-tests v4.2.9 requires phpcompatibility/php-compatibility (^9.3.5) 
```

**Comment by ernilambar** [comment]
```
 Root composer.json requires php >=7.2.24 but your php version (5.6.40) does not satisfy that requirement.
```

Tests in PHP 5.6 will fail as now min PHP requirement is `7.2.24`

**Comment by swissspidy** [comment]
I don‘t understand, where do you see this happening?

phpcompatibility/php-compatibility requires 5.4, not 7.2

**Comment by ernilambar** [comment]
I got this error in the first run. https://github.com/ernilambar/database-command/actions/runs/10438520540/job/28905938295

Now it is not appearing. 🙄
