### ISSUE TITLE
Update dealerdirect/phpcodesniffer-composer-installer version

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/wp-cli-tests#30]
In my project I'm requiring version `^0.5` of [`dealerdirect/phpcodesniffer-composer-installer`](https://packagist.org/packages/dealerdirect/phpcodesniffer-composer-installer). This package currently requires `^0.4.3`, which means I cannot install it and the other package at the same time, at least not if I want to use version `0.5`.

I suggest changing the requirement for `dealerdirect/phpcodesniffer-composer-installer` from `^0.4.3` to `^0.5`.

**Comment by swissspidy** [comment]
I tried to fix this in the `fix/required-dependency-version` branch but somehow the precommit hooks don't work and now there are a bunch of changes to the readme every time I try to commit the change to `composer.json`. Ugh.

**Comment by schlessera** [comment]
@swissspidy The problem with the `README.md` changes should have been solved by https://github.com/wp-cli/wp-cli-tests/pull/32

**Comment by schlessera** [comment]
Versions with `0.x.x` are handled differently than anything above `1.0.0`, so this is considered a major bump here.

The version constraint should be `^0.4.3 || ^0.5` for now.
