### ISSUE TITLE
Make the PHPCS setup more reusable

### ISSUE THREAD

**Issue by jrfnl** [wp-cli/wp-cli-tests#34]
Would you be interested in a PR which will make the PHPCS setup re-usable by other WP-CLI packages ? (including documentation on how to use)

**Comment by jrfnl** [comment]
As a side-note: the current ruleset effectively excludes **all** files in this repo from the PHPCS check, so not sure what the intention was....

**Comment by jrfnl** [comment]
While what I have in mind is quite possible with the current PHPCS requirements, it will be more flexible if a minimum PHPCS requirement of `^3.1.1` is set.

WPCS 2.0 will have PHPCS 3.x (probably 3.3.1) as a minimum anyway, so once that's out and the dependency has been updated, this won't have to be made specific anymore, but as WPCS 1.x still supports PHPCS 2.x, it might be a good idea to (temporarily) set a WP_CLI specific PHPCS requirement.

If you want to be able to use the new selective PHPCS annotations as well, I would recommend setting it to `^3.2`, though quite some sniffs are still buggy for handling the PHPCS annotations in that version, so with that in mind `^3.2.3` would be better.

And if you don't want to worry about people running it on PHP 7.3, then the minimum requirement should be `^3.3.1` as that version contains a compatibility fix to PHPCS for PHP 7.3.

**Comment by jrfnl** [comment]
Also: the WP variable naming rules are explicitly excluded. Is there another standard for variable naming which is consistently used and should be enforced ? PSR2 maybe ?

Similarly, for the file name rules.

**Comment by schlessera** [comment]
@jrfnl As we're using a separate "Sniff" stage in Travis that we can set the PHP version of independently, we don't need to stick with the PHP minimum requirement of 5.4+ here. So I don't see an issue with using `^3.3.1` as a minimum requirement.

**Comment by schlessera** [comment]
Oh, in case that was not obvious...

> Would you be interested in a PR which will make the PHPCS setup re-usable by other WP-CLI packages ? (including documentation on how to use)

**Yes, please! :)**

**Comment by schlessera** [comment]
> As a side-note: the current ruleset effectively excludes all files in this repo from the PHPCS check, so not sure what the intention was....

This file here was meant to be the source to use for scaffolding new packages.

But making the ruleset reusable is even better!

**Comment by jrfnl** [comment]
> As we're using a separate "Sniff" stage in Travis that we can set the PHP version of independently, we don't need to stick with the PHP minimum requirement of 5.4+ here. So I don't see an issue with using ^3.3.1 as a minimum requirement.

The minimum PHP requirement for PHPCS 3.x is still PHP 5.4, it's only the maximum which is an issue when using PHPCS < 3.3.1.

> This file here was meant to be the source to use for scaffolding new packages.

No worries, but if it's not used for this package, it might be better not to give the impression it is. I.e. removing the custom project ruleset + removing the composer script + removing the Travis call. (Only for projects - like this - where using PHPCS is not yet implemented)

Would you like me to do so ?

N.B.: Doing so will not get in the way of shipping a reusable ruleset for the other projects from within this repo.

> Yes, please! :)

Ok, will get this sorted for you, but I do have some questions which need input.

> the WP variable naming rules are explicitly excluded. Is there another standard for variable naming which is consistently used and should be enforced ? PSR2 maybe ?
>
> Similarly, for the file name rules.

:point_up: Input on this would be welcome.
* Is this valid for all WP-CLI projects ?
* Is there another rule you use consistently for variable names ? (I don't need the sniff name or anything, just to know whether you want to enforce something and if so, what ?
* Same question for the file names.

More questions:
* Am I correct in thinking that WP-CLI projects generally only have PHP code ? No JS or CSS files ?
* Is the exclusion of the `Squiz.PHP.DisallowMultipleAssignments` sniff something that is supposed to happen for all WP-CLI projects ? or only for select projects ?
* Are there any devs involved with WP-CLI using Windows ? (aside from me)

Also, I get the impression that not all WP-CLI projects use the same minimum PHP version. Is that correct ? Or should they all use the same minimum version (and some just haven't been updated yet) ? And if so, which version is the minimum ?

Oh and last question: is the `array_column()` polyfill package available to **all** WP-CLI projects ? or only to a select number of them ?

Ok, I think that's it. Once I have the answers, you'll have your PR :sunglasses:

**Comment by schlessera** [comment]
> No worries, but if it's not used for this package, it might be better not to give the impression it is. I.e. removing the custom project ruleset + removing the composer script + removing the Travis call. (Only for projects - like this - where using PHPCS is not yet implemented)
> 
> Would you like me to do so ?

No, please leave the file in there for now. The packages are set up so that the sniffs don't run if there is no config file, so removing the config file would already be enough. But I'll want to see first what it means to have this be reusable, and then coordinate it across packages first before doing any removals.

> the WP variable naming rules are explicitly excluded. Is there another standard for variable naming which is consistently used and should be enforced ? PSR2 maybe ?
> 
> Similarly, for the file name rules.

The variables are currently a legacy mess, so enforcing them would require renaming a lot of methods first. Let's skip enforcing that for now. Same for filenames. I'm sticking to PSR-4 usually, but we have lots of procedural code still.

> Am I correct in thinking that WP-CLI projects generally only have PHP code ? No JS or CSS files ?

Generally, yes. The only package that contains JS and CSS files is the `wp-cli/scaffold-command` package. However, these should come in the form of templates, not final files. Testing them will require special consideration anyway.

> Is the exclusion of the Squiz.PHP.DisallowMultipleAssignments sniff something that is supposed to happen for all WP-CLI projects ? or only for select projects ?

I actually ignore why we have that exclusion. I'd suspect there's only a handful of occurrences of this anyway, so it might be easier to fix these and remove the exclusion. I'll have to check that, though.

> Are there any devs involved with WP-CLI using Windows ? (aside from me)

Some contributors use Windows indeed.

**Comment by jrfnl** [comment]
@schlessera Thanks for that, nearly done. Just those last question about PHP version support I still need answers for:

> Also, I get the impression that not all WP-CLI projects use the same minimum PHP version. Is that correct ? Or should they all use the same minimum version (and some just haven't been updated yet) ? And if so, which version is the minimum ?
>
> Oh and last question: is the array_column() polyfill package available to all WP-CLI projects ? or only to a select number of them ?

**Comment by jrfnl** [comment]
@schlessera Actually, one more question: is the code from the WP-CLI commands always run in the context of WP ? I.e. is WP always fully loaded ? I didn't think it was, but want to make sure.

**Comment by jrfnl** [comment]
Just FYI: I've ran I have so far over some four randomly picked repos in this organization to see where it needed tweaking and have fixed up nearly everything in those repos along the way.

I can pull those fixes independently of the changes here. Doing so will make it easier for those repos to adopt PHPCS once this issue has been closed.
Shall I ?

**Comment by schlessera** [comment]
> Also, I get the impression that not all WP-CLI projects use the same minimum PHP version. Is that correct ? Or should they all use the same minimum version (and some just haven't been updated yet) ? And if so, which version is the minimum ?

With version 2.0.0 of the framework, I bumped the required minimum to PHP 5.4+ for the framework, and all packages with a v2.x.x version should be the same. There might be one or two that haven't been moved over yet, but they all eventually will.

> Oh and last question: is the array_column() polyfill package available to all WP-CLI projects ? or only to a select number of them ?

It's part of the framework package (`wp-cli/wp-cli`), so available to everything else as well.

**Comment by schlessera** [comment]
> Actually, one more question: is the code from the WP-CLI commands always run in the context of WP ? I.e. is WP always fully loaded ? I didn't think it was, but want to make sure.

No, there's WP-CLI hooks in place and commands can choose to hook in there and execute earlier, like for example execute on `@before-wp-load`. This is for example the case for the  `wp-cli/db-command` commands that use `mysql` to prepare the DB.

**Comment by schlessera** [comment]
> I can pull those fixes independently of the changes here. Doing so will make it easier for those repos to adopt PHPCS once this issue has been closed.
Shall I ?

Yes, sounds good.
