### ISSUE TITLE
Abandoned dependencies

### ISSUE THREAD

**Issue by aaemnnosttv** [wp-cli/wp-cli-tests#48]
After installing, Composer warns about these abandoned dependencies:

```
Package ramsey/array_column is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
```

**Comment by schlessera** [comment]
Related: https://github.com/wp-cli/wp-cli/issues/5061

**Comment by schlessera** [comment]
Fixed via https://github.com/wp-cli/wp-cli/pull/5126

**Comment by schlessera** [comment]
The issue was only solved for `ramsey/array_column`.
 
`phpunit/phpunit-mock-objects` will need us to update PHP Unit.

**Comment by schlessera** [comment]
Should be fixed now that we let the PHPUnit Polyfills manage the PHPUnit dependency.
