### ISSUE TITLE
Move WPCS to v2.2.0

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli-tests#73]
The current version of WPCS is not yet compatible with PHP 7.4+.

As soon as the [release process for WPCS v2.2.0](https://github.com/WordPress/WordPress-Coding-Standards/pull/1828) is completed, we should move our linting to PHPCS v3.5.2+ and WPCS 2.2.0+ to get PHP 7.4+ linting to work.

**Comment by jrfnl** [comment]
WPCS 2.2.0 has been released ;-)

**Comment by jrfnl** [comment]
While you're at it, it would be a good idea to also update PHPCompatibility where necessary. The latest release - 9.3.3 - came out today as well.

**Comment by schlessera** [comment]
Thanks for all of your awesome work, @jrfnl ! ❤️

**Comment by schlessera** [comment]
This was already completed and we're currently requiring v2.3+.
