### ISSUE TITLE
Setup issue, native wp functions not found, inability to complete prepare-tests

### ISSUE THREAD

**Issue by RichDavis1** [wp-cli/wp-cli-tests#84]
After installing everything according to the docs, phpunit is still unable to find native wp functions such as 'get_user_meta'.

Am I missing a step? I have wp-cli/wp-cli-tests autoloaded & composer has been updated with autoload optimized.

Only step I believe that's missing is composer prepare-tests which logs the following error:
```ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)```

When I add a password to the install-package-tests.sh file ```mysql -e 'CREATE DATABASE IF NOT EXISTS wp_cli_test;' -uroot -p[pw]``` the script hangs.

Any help would be greatly appreciated.

**Comment by schlessera** [comment]
@RichDavis1 Come into Slack on the #cli channel (there's currently office hours), and we can then troubleshoot interactively.

> GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

> The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
